version: '3.9'

services:
    web-client:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - '8000:8000'
